# Generated by Django 3.0 on 2020-09-10 09:35

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('hobby', models.CharField(blank=True, max_length=200)),
                ('favorite_quotes', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('grade', models.CharField(blank=True, choices=[('1-5', 'One to Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('11', 'Eleven'), ('12', 'Twelve'), ('HA', 'Health Assistant'), ('Diploma in Engineering', 'Diploma'), ('Bachelor in CSIT', 'Bachelor in CSIT'), ('Bachelor in Agriculture', 'Bachelor in Agriculture'), ('Diploma in Agriculture', 'Diploma in Agriculture'), ('Bachelor in Engineering', 'Bachelor in Engineering'), ('Bachelor in Education', 'Bachelor in Education'), ('Bachelor in Commerce', 'Bachelor in Commerce'), ('BSC Nursing', 'Bachelor in Nursing'), ('Bachelor in CSIT', 'Bachelor in CSIT'), ('General', 'General')], max_length=200)),
                ('schoolType', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Art', 'Art'), ('Medicine', 'Medicine'), ('Engineering', 'Engineering'), ('Computer Science', 'Computer Science')], max_length=200)),
                ('schoolName', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
