# Generated by Django 3.0 on 2020-09-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200910_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schoolType',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Art', 'Art'), ('Medicine', 'Medicine'), ('Engineering', 'Engineering'), ('Computer Science', 'Computer Science')], max_length=200),
        ),
    ]
