# Generated by Django 3.0 on 2020-09-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, choices=[('One to Five', 'One to Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten'), ('Eleven', 'Eleven'), ('Twelve', 'Twelve'), ('HA', 'Health Assitant'), ('Staff Nurse', 'Staff Nurse'), ('Diploma in Agriculture', 'Diploma in Agriculture'), ('Diploma in Engineering', 'Diploma in Engineering'), ('Bachelor in CSIT', 'Bachelor in CSIT'), ('BSC Nursing', 'BSC Nursing'), ('Bachelor in Education', 'Bachelor in Education'), ('Bachelor in Engineering', 'Bachelor in Engineering'), ('BBS', 'BBS'), ('BBA', 'BBA'), ('MBBS', 'MBBS'), ('General', 'General')], max_length=200),
        ),
    ]
