# Generated by Django 3.0 on 2020-09-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200916_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='../static/images/Flag_of_Nepal.png', null=True, upload_to='profile'),
        ),
    ]
