# Generated by Django 3.0 on 2020-09-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200918_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='../static/images/Flag_of_Nepal.png', upload_to='profile'),
        ),
    ]
