# Generated by Django 3.0 on 2020-09-17 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Book Name')),
                ('status', models.DateField()),
                ('participatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participatedByOther', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Book Name')),
                ('writer', models.CharField(max_length=200, verbose_name='Book Writer')),
                ('summary', models.TextField(max_length=1000)),
                ('date', models.DateField()),
                ('participatedBy', models.ManyToManyField(related_name='participatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
