# Generated by Django 3.0 on 2020-10-18 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extrapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStarted', models.DateField(auto_now_add=True)),
                ('doneReading', models.BooleanField(default=False, verbose_name='Done Reading Book?')),
            ],
        ),
        migrations.RemoveField(
            model_name='currentbook',
            name='participatedBy',
        ),
        migrations.AddField(
            model_name='currentbook',
            name='coverImage',
            field=models.ImageField(null=True, upload_to='readnepal', verbose_name='Book Cover Image'),
        ),
        migrations.AddField(
            model_name='currentbook',
            name='isItCurrentBook',
            field=models.BooleanField(default=False, verbose_name='Is this a Book of Month'),
        ),
        migrations.DeleteModel(
            name='OtherBook',
        ),
        migrations.AddField(
            model_name='participiant',
            name='bookName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookName', to='extrapp.CurrentBook'),
        ),
        migrations.AddField(
            model_name='participiant',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL),
        ),
    ]
