# Generated by Django 3.0 on 2020-10-18 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extrapp', '0002_auto_20201018_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentbook',
            name='reader',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
