# Generated by Django 3.0 on 2020-10-18 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extrapp', '0003_currentbook_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbook',
            name='reader',
            field=models.ManyToManyField(blank=True, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
