# Generated by Django 3.0 on 2020-10-18 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extrapp', '0004_auto_20201018_1212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participiant',
            unique_together={('reader', 'bookName')},
        ),
    ]
