# Generated by Django 3.0 on 2020-09-13 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('categoty', models.CharField(max_length=100, verbose_name='Category')),
                ('grade', models.CharField(max_length=100, verbose_name='Class')),
                ('detail', models.TextField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('answered_status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('askedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField()),
                ('answer_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_ondiscussion', to='discussion.Discussion')),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
