# Generated by Django 3.0 on 2020-09-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='categoty',
        ),
        migrations.AddField(
            model_name='discussion',
            name='subject',
            field=models.CharField(default=1, max_length=100, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='answered_status',
            field=models.BooleanField(default=False, verbose_name='Is your question answered'),
        ),
    ]
