# Generated by Django 3.0 on 2020-09-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_auto_20200913_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Is discussion Pinned'),
        ),
    ]
