# Generated by Django 3.0 on 2020-09-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_discussion_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(default=1, max_length=550, verbose_name='Slug Fields'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='grade',
            field=models.CharField(choices=[('One to Five', 'One to Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten'), ('Eleven', 'Eleven'), ('Twelve', 'Twelve'), ('HA', 'Health Assitant'), ('Staff Nurse', 'Staff Nurse'), ('Diploma in Agriculture', 'Diploma in Agriculture'), ('Diploma in Engineering', 'Diploma in Engineering'), ('Bachelor in CSIT', 'Bachelor in CSIT'), ('BSC Nursing', 'BSC Nursing'), ('Bachelor in Education', 'Bachelor in Education'), ('Bachelor in Engineering', 'Bachelor in Engineering'), ('BBS', 'BBS'), ('BBA', 'BBA'), ('MBBS', 'MBBS'), ('General', 'General')], max_length=100, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='subject',
            field=models.CharField(choices=[('physic', 'Physic'), ('chemistry', 'Chemistry'), ('botany', 'Botany'), ('zoology', 'Zoology'), ('math', 'Math'), ('english', 'English'), ('nepali', 'Nepali'), ('science', 'science'), ('social', 'Social'), ('eph', 'Environement,Population and Health'), ('Opt', 'Optional Math'), ('cs', 'Computer Science'), ('account', 'Account'), ('business', 'Business'), ('marketing', 'Marketing'), ('general', 'General')], max_length=100, verbose_name='Subject'),
        ),
    ]
