# Generated by Django 3.0 on 2020-09-10 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255)),
                ('content', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('grade', models.CharField(choices=[('1-5', 'One to Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('11', 'Eleven'), ('12', 'Twelve'), ('Bachelor', 'Bachelor'), ('General', 'General')], default='General', max_length=20)),
                ('subject', models.CharField(choices=[('physic', 'Physic'), ('chemistry', 'Chemistry'), ('botany', 'Botany'), ('zoology', 'Zoology'), ('math', 'Math'), ('english', 'English'), ('nepali', 'Nepali'), ('science', 'science'), ('social', 'Social'), ('eph', 'Environement,Population and Health'), ('Opt', 'Optional Math'), ('cs', 'Computer Science'), ('account', 'Account'), ('business', 'Business'), ('marketin', 'Marketing'), ('general', 'General')], default='General', max_length=25)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likedpost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
