# Generated by Django 3.0 on 2020-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='grade',
            field=models.CharField(choices=[('1-5', 'One to Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('11', 'Eleven'), ('12', 'Twelve'), ('Bachelor', 'Bachelor'), ('General', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(choices=[('physic', 'Physic'), ('chemistry', 'Chemistry'), ('botany', 'Botany'), ('zoology', 'Zoology'), ('math', 'Math'), ('english', 'English'), ('nepali', 'Nepali'), ('science', 'science'), ('social', 'Social'), ('eph', 'Environement,Population and Health'), ('Opt', 'Optional Math'), ('cs', 'Computer Science'), ('account', 'Account'), ('business', 'Business'), ('marketin', 'Marketing'), ('general', 'General')], max_length=25),
        ),
    ]
